### ISSUE TITLE
Публикация в bower

### ISSUE THREAD

**Issue by prog666** [ilyabirman/Likely#1]
http://bower.io/ Очень нехватает.

**Comment by volter9** [comment]
Теперь можно установить Лайкли через bower:

```sh
bower install ilyabirman-likely
```

**Comment by prog666** [comment]
Спасибо! =)14.10.2015, 17:13, "volter9" <notifications@github.com>:Теперь можно установить Лайкли через bower:

bower install ilyabirman-likely

**Comment by prog666** [comment]
(можно до кучи еще и в npm)14.10.2015, 17:13, "volter9" <notifications@github.com>:Теперь можно установить Лайкли через bower:

bower install ilyabirman-likely

**Comment by volter9** [comment]
> (можно до кучи еще и в npm)

Уже давно есть :)

    npm install ilyabirman-likely

**Comment by prog666** [comment]
Там не прописаны main файлы и нет скомпиленного js файла. Вообще я бы сделал в самой папке репозитория папку dist и просто добавил бы ее в .gitignore, то что сейчас - что-то странное.

**Comment by volter9** [comment]
> Там не прописаны main файлы и нет скомпиленного js файла. Вообще я бы сделал в самой папке репозитория папку dist и просто добавил бы ее в .gitignore, то что сейчас - что-то странное.

Добавил main поле в bower.js и скомпилированные файлы. Назвал папку `release` т.к. Бирман, вроде бы, не любит сокращенные названия вроде lib, src, dist, etc. :)

Интересно, а можно ли как нибудь добавить скомпилированные файлы в bower и npm, но чтобы они не были в git репозитории?

**Comment by prog666** [comment]
можно =)

**Comment by volter9** [comment]
А как? :)

**Comment by prog666** [comment]
вру, в гит репозитории будут все равно потому что bower берет из гита, сам компилить он не может, но можно в bower и package.json заигнорить все исходники. [тут](https://github.com/prog666/tabs) пример
