### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by mrserge** [ilyabirman/Likely#10]
TypeError: Cannot read property 'counter' of undefined
http://leningrad.lv/addons/likely/likely.js:4

Have no idea is it a bug or what.

**Comment by volter9** [comment]
Which browser does causing this error? If it's IE9, I think it won't fix.

**Comment by mrserge** [comment]
Chrome Version 46.0.2490.86 m, Windows 10.

**Comment by volter9** [comment]
Hm, I just tested latest likely on the latest version of chrome (the one that you've mentioned) on OS X, and everything works fine. Could you provide additional details:

* Which version of likely are you using?
* How do you include likely on page?
* How do you initiate likely (if you including the file in `release` folder, or via bower then skip this question)?

**Comment by volter9** [comment]
I found the error on your website, I'll try to inspect, what the problem might be.

**Comment by volter9** [comment]
I found the error, remove the <br> tags for now, Likely tries to load <br> tags as widgets.

**Comment by volter9** [comment]
Fixed in new version v2.0.6 (852bef7)
