### ISSUE TITLE
Проблема с ининцализацией

### ISSUE THREAD

**Issue by mdorfin** [ilyabirman/Likely#11]
Иногда виджет инициализируется только после перезагрузки страницы
Например http://www.eyeseestyle.com/en/diary/big-geometric-earrings внизу поста.

**Comment by volter9** [comment]
English, please :) 

I don't really see the problem, could you elaborate what the problem is?

**Comment by volter9** [comment]
No response for few days. Is your issue already solved?

**Comment by volter9** [comment]
I don't see the issue, and you seem to solve your issue too. I'll close the issue, then.

**Comment by mdorfin** [comment]
Sorry, it was a problem with initialization. The fix is remove turbolinks gem from the project. :)
