### ISSUE TITLE
Ошибка в IE 11

### ISSUE THREAD

**Issue by Shperung** [ilyabirman/Likely#112]
В IE 11 не работает вывод. Выводит ошибку 

> Объект не поддерживает свойство или метод "from"  

 [http://c2n.me/3FWMBqh](url)

**Comment by vitkarpov** [comment]
А что за ссылка странная? :) Видимо, на скриншот со стектрейсом, но ведет ссылка куда-то не туда.

**Comment by Shperung** [comment]
Да это скринншот. Показал что в библиотеке один раз встречается функция Array.from и IE 11 не видит ее. Читал по поводу этой функции, пишет что Internet Explorer No support 

[https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from](url)

**Comment by iamakulov** [comment]
@Shperung, спасибо! Мы постараемся починить поскорее.

**Comment by vitkarpov** [comment]
@Shperung 

> А что за ссылка странная?

Сорри, ссылка нормальная. Просто почему-то гитхаб по всем ссылкам ведет не туда (все ссылки здесь ведут на .../issues/url)

**Comment by vitkarpov** [comment]
https://github.com/ilyabirman/Likely/releases/tag/v2.2.1

**Comment by vitkarpov** [comment]
@Shperung Привет! Попробуй поставить версию 2.2.1

**Comment by Shperung** [comment]
Спасибо с версией 2.2.1 в IE 10/11 все работает
