### ISSUE TITLE
updateCounter uses find which is not defined in this scope

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#114]
updateCounter [uses find](https://github.com/ilyabirman/Likely/blob/master/source/button.js#L158) but [there's no import of this method](https://github.com/ilyabirman/Likely/blob/master/source/button.js#L1) from `dom.js`.

So, Uglifyjs just drops it from bundle 

![2016-12-28_18-07-38](https://cloud.githubusercontent.com/assets/3001791/21524626/91b59d2e-cd28-11e6-92a2-2a11d5f9fb6a.png)

Seems `updateCounter` should not work as expected

**Comment by iamakulov** [comment]
Woah. Seems like this uses non-standard [`window.find`](https://developer.mozilla.org/en-US/docs/Web/API/Window/find) which luckily evaluates to false and doesn’t cause an exception a couple of lines further. Thanks for noticing!

Can we get this into 2.2.1?

**Comment by vitkarpov** [comment]
> Seems like this uses non-standard window.find

Exactly!

![2016-12-28_18-44-47](https://cloud.githubusercontent.com/assets/3001791/21525336/c2465db6-cd2d-11e6-9967-3906ba571e14.png)


Also turns out that we don't have tests which cover the case, I mean `updateCounter` works but not as expected in case when `find` should return `true` but we don't know it.

**Comment by vitkarpov** [comment]
> Can we get this into 2.2.1?

Absolutely!

**Comment by iamakulov** [comment]
> Absolutely!

Thanks!

**Comment by vitkarpov** [comment]
https://github.com/ilyabirman/Likely/releases/tag/v2.2.1
