### ISSUE TITLE
Comeback likes after migrating from http to https

### ISSUE THREAD

**Issue by regme07** [ilyabirman/Likely#124]
After migrating from http to https I have lost all my likes to posts. Can you make configurable option to return likes, for example in the way it describes at
https://www.kayakonlinemarketing.com/blog/preserving-sharing-counts-when-migrating-to-https-or-another-domain

**Comment by iamakulov** [comment]
There’s already an option for this. You can specify the page URL with the `data-url` parameter ([docs](https://github.com/ilyabirman/Likely#common-options)):

```html
<div class="likely" data-url="your url with http instead of https"></div>
```

I’m closing the issue for now, but if you have any questions or problems with this solution, feel free to comment!
