### ISSUE TITLE
Global function "random_fun_{n}"

### ISSUE THREAD

**Issue by arlegotin** [ilyabirman/Likely#126]
Plugin clogs global scope with functions which are called "random_fun_1", "random_fun_2" and etc.
The call to this function changes value of "google+" counter in all instances:

![screen shot 2017-04-18 at 21 45 38](https://cloud.githubusercontent.com/assets/1470560/25147642/e3edf7a8-2480-11e7-9a4f-7f9811ce8341.png)

**Comment by vitkarpov** [comment]
@arlegotin Hey, Artem! Thanks for feedback, I'll look at this until the end of the week. Clogging isn't good at all :)
