### ISSUE TITLE
Can't focus on likely buttons with keyboard

### ISSUE THREAD

**Issue by paulradzkov** [ilyabirman/Likely#129]
Accessibility issue.  
Can't navigate likely buttons with `Tab` or `Shift + Tab` shortcuts.
Can't interact with buttons using Voice Over.

Consider adding `tabindex` or converting buttons into links for graceful degradation and better accessibility.

**Comment by paulradzkov** [comment]
Minimum required modifications:
* add `tabindex="0"`
* add `role="link"` or `role="button"`. I think «link» fits better.
* optional, add `aria-label="Share on Twitter"` 

See https://www.youtube.com/watch?v=qOe2UA6PHAc for example

**Comment by paulradzkov** [comment]
Tested the markup referenced in pull request — works fine with Voice Over and keyboard navigation.

But I believe Likely should add those attributes by itself when they are not provided by user.

**Comment by iamakulov** [comment]
> But I believe Likely should add those attributes by itself when they are not provided by user.

Thanks! We’ll probably implement this in a future version.

**Comment by iamakulov** [comment]
Closed in #130.
