### ISSUE TITLE
Using with webpack

### ISSUE THREAD

**Issue by Corey-Maler** [ilyabirman/Likely#13]
Hello! Please, extend documentation with next:

## Using with webpack
First, make sure that you install [json-loader](https://github.com/webpack/json-loader)

Next install **likely** via npm

Then, in code: 
``` javascript
\\ on document ready or in the end
require('ilyabirman-likely').initiate();
```

Thanks!

**Comment by volter9** [comment]
Done! Thanks for contribution!
