### ISSUE TITLE
vk.com - 'image' parameter

### ISSUE THREAD

**Issue by coldshine** [ilyabirman/Likely#136]
`vk.com/share.php` seems started to use new GET parameter called `image`.
 
For example to make a post with an image from a cell-phone we have to use this param, because `m.vk.com/share.php` skips `og:image` tag...

**Comment by iamakulov** [comment]
Do you mean this as a question?

If so, yes, [you can specify the `data-image` attribute](https://github.com/ilyabirman/Likely#vk) on the VK button to use this GET parameter:

```
<div class="likely">
  <div class="vkontakte" data-image="https://placekitten.com/200/400" data-description="Check this out">Share</div>
</div>
```

If I haven’t understood you, feel free to correct me!

**Comment by coldshine** [comment]
Oh, yeah, you're right! I just've missed this part of docs. 
Thank you!
