### ISSUE TITLE
WhatsApp on Safari

### ISSUE THREAD

**Issue by glutaminefree** [ilyabirman/Likely#139]
Hi!
Thanks for good tool!
But whatsapp button don't work on Safari 10. Version of library is 2.3.0. I checked on your project demo page too.

Browser console says: ```TypeError: Attempted to assign to readonly property.```

**Comment by iamakulov** [comment]
@glutaminefree, thank you for the report!

Safari 11 came out. Could you please try to reproduce this issue in it?

**Comment by glutaminefree** [comment]
@iamakulov, In Safari 11 this error gone.

**Comment by iamakulov** [comment]
Thanks! I'll consider this fixed then.
