### ISSUE TITLE
'Refuse to execute script' error in Chrome

### ISSUE THREAD

**Issue by konclave** [ilyabirman/Likely#14]
On script load there's an error in console: 
`Refused to execute script from 'http://share.yandex.ru/gpp.xml?gid=0&url=http%3A%2F%2Fnanobilet.local.ticketscloud.org%2Fe%2F55d468139cb53842cb27ec03' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

Chrome / MacOS

**Comment by volter9** [comment]
Sup. Thank you for reporting the issue. I'll check the problem tomorrow or ASAP.

**Comment by volter9** [comment]
Fixed in [v2.0.8](https://github.com/ilyabirman/Likely/releases/tag/v2.0.8).
