### ISSUE TITLE
Как взять картинку из статьи, если likeley имеет data-url?

### ISSUE THREAD

**Issue by agragregra** [ilyabirman/Likely#142]
Как взять картинку из статьи, если likeley имеет data-url?
Есть параметр data-media, который, как я понял, работает только с Pinterest.
< meta property="og:image" content="path/to/image" > - берет картинку с текущей страницы.
Но если Likeley расположен в айтеме на странице категории блога и берет url нужной статьи, как взять картинку именно этой статьи для публикации в соц-сети?

**Comment by iamakulov** [comment]
Привет!

Мы можем подставлять соцсетям произвольные картинки только с Пинтересом и ВК. Остальные соцсети обычно сами подтягивают картинку из тега `<meta property="og:image" content="path/to/image">` с той странички, которой вы делитесь (то есть той страницы, которая в `data-url`).

Поэтому, если у вас есть кнопка с `data-url="example.com/path/to/page"`, то:

* Если вы можете редактировать страницу `example.com/path/to/page`, добавьте туда тег `<meta property="og:image" content="path/to/image">` с той картинкой, которую вы хотите утащить в соцсети.
* Если вы не можете редактировать ту страницу, но вы настраиваете кнопку Пинтереса или ВК, добавьте на кнопку атрибут [`data-media`](https://github.com/ilyabirman/Likely#pinterest) или [`data-image`](https://github.com/ilyabirman/Likely#vk) соответственно.
* Если вы не можете редактировать страницу и хотите настроить другие кнопки, то Лайкли тут никак не помогут :–(

Я закрою этот ишью, но если у вас ещё будут вопросы по теме, пишите.

**Comment by agragregra** [comment]
Спасибо, не знал о такой особенности. То, что нужно.
