### ISSUE TITLE
Use rel=canonical as an additional source of url parameter

### ISSUE THREAD

**Issue by paulradzkov** [ilyabirman/Likely#19]
Likely buttons should search for url to share in the following places by order:

1. own `data-url` attribute 
2. `<link rel="canonical" href="..." />` in the head of the page
3. the address of the page

According to https://yoast.com/rel-canonical/ :

> Facebook and Twitter honor rel=canonical too. This might lead to weird situations. If you share a URL on Facebook that has a canonical pointing elsewhere, Facebook will share the details from the canonical URL. In fact, if you add a like button on a page that has a canonical pointing elsewhere, it will show the like count for the canonical URL, not for the current URL. Twitter works in the same way.

If the page already has `rel=canonical` Likely should use it. On www and non www domains, on any other mirrors and even on localhost Likely will share correct url and show correct number of shares without additional settings.

**Comment by iamakulov** [comment]
Good point, thank you! PRs are welcome.

**Comment by iamakulov** [comment]
Done! #37
