### ISSUE TITLE
How to reinitialize the buttons after AJAX call?

### ISSUE THREAD

**Issue by ZuevEvgenii** [ilyabirman/Likely#22]
How I can reinit it after AJAX call?

**Comment by navstyachka** [comment]
If you have only one instance of sharing block, try `likely.initiate()`.

**Comment by iamakulov** [comment]
@ZuevEvgenii, why do you need to re-initialize the buttons? What’s the use case?

**Comment by iamakulov** [comment]
I’m closing this now, but I still would be happy to answer. Just leave a comment here if you need help in this questing.
