### ISSUE TITLE
Unused global variables

### ISSUE THREAD

**Issue by designeng** [ilyabirman/Likely#24]
I researched source, but I can't guess the reason for creating global variables in [dom.js](https://github.com/ilyabirman/Likely/blob/master/source/dom.js#L58). Are they necessary?

**Comment by makingoff** [comment]
@designeng the way of getting data from this counters in passing name of callback function and wait for getting request on them. This script adds `<script src="htttp://path-to-counter?callback=${funcname}"></script>` and wait to save data in this function, for example https://github.com/ilyabirman/Likely/blob/master/source/services/vk.js#L24 It solves some problems with crossdomain requests.

**Comment by designeng** [comment]
@makingoff, thanks a lot for you explanation!
