### ISSUE TITLE
Buttons remain pressed after first tap on iOS 9

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#25]
From an email:

> Под 9 ios на 5м айфоне Сафари дает нажать на каждую из кнопок только один раз. Потом она остается нажатой. Нужно перегружать сайт - тогда опять можно нажать по одному разу. Проверяли на нескольких телефонах (Ось 9.0.3, версия Сафари зависит именно от нее)

Environment: iOS 9, Safari.

**Comment by vitkarpov** [comment]
Seems it's a `:hover`, isn't it? iOS handles :hover as a first tap, so the hover state remains after touch ends. If you tap somewhere in the document does it take off "the pressed state" from the button?

**Comment by iamakulov** [comment]
Probably. I don’t have an iOS device, but if someone does, could you please test the buttons there and let us know if tapping in the document fixes the buttons? You can try here: http://ilyabirman.net/projects/likely/.

**Comment by vitkarpov** [comment]
It really does. Also document click restores the state. You can check it
without real device also, using chrome dev tools

воскресенье, 1 мая 2016 г. пользователь Ivan Akulov написал:

> Probably. I don’t have an iOS device, but if someone does, could you
> please test the buttons there and let us know if tapping in the document
> fixes the buttons? You can try here:
> http://ilyabirman.net/projects/likely/.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ilyabirman/Likely/issues/25#issuecomment-216048461>
>


-- 
Виктор.

**Comment by vitkarpov** [comment]
Usually in such cases 2 versions of css are made: `project.css` and `project.touch.css`. The second doesn't contain `:hover`, so the problem vanishes.

Is it okay for you to configure your site in such way: if the user comes from touch device to include another css for likely?

**Comment by ilyabirman** [comment]
I suspect it would be wiser to support this behaviour out of the box. Can this be implemented in CSS media queries, for example?

Looks like is CSS 4 they are going to add media queries specifically for this:
http://www.quirksmode.org/css/tests/mediaqueries/hover.html

**Comment by iamakulov** [comment]
Great, didn’t know about the `hover` media feature. [MDN reports that Safari 9.3 supports it](https://developer.mozilla.org/en/docs/Web/CSS/@media/hover) so this looks like a good solution.

**Comment by vitkarpov** [comment]
It's a good point, but unfortunately it doesn't work in IOS < 9 yet. Maybe we should use it anyway?

**Comment by vitkarpov** [comment]
Another way is to use a simple js to detect touch device and set a global class to body, so it's possible to make a distinguish in css.

**Comment by iamakulov** [comment]
> It's a good point, but unfortunately it doesn't work in IOS < 9 yet. Maybe we should use it anyway?

As of February, [77% of iOS devices run iOS 9](http://www.macrumors.com/2016/02/24/ios-9-adoption-rate-stalls-at-77/). @ilyabirman, we don’t declare the supported browser versions, but could we officially drop iOS 8 support?

> Another way is to use a simple js to detect touch device and set a global class to body, so it's possible to make a distinguish in css.

I don’t like adding classes to `body` because it modifies the document state outside of Likely. I’d rather check the touch device with JavaScript and include an additional stylesheet with hover styles when necessary.

**Comment by vitkarpov** [comment]
> I don’t like adding classes to body because it modifies the document state outside of Likely.

Yep, totally. Anyway there's a way to add some styles dynamically. Seems it's simpler to use css4.

**Comment by iamakulov** [comment]
Important node: if we use `@media (hover)` to declare the `hover` styles, we should also use `@supports` to enable the styles in the browsers that don’t support the `@media (hover)` feature. This breaks Likely in IE 11 and below [as they don’t support `@supports`](http://caniuse.com/#feat=css-featurequeries).

**Comment by ilyabirman** [comment]
If this issue is fixed only in iOS 9, I’m fine with it.

To workaround the IE problem, could we maybe use @media (not hover) somehow to undeclare the hover styles? :-)

**Comment by iamakulov** [comment]
Have thought of it, but unsure that this is possible. We’ll still have to add the `:hover` pseudoclass, which will most likely trigger this undesired behavior.

Anyway, I’ll try this solution.

**Comment by iamakulov** [comment]
I’ve tried implementing a `@media (hover)` solution. It applies the hover styles and then unsets them inside of the media block:

```less

.likely__widget_{button} {
  fill: color;

  &:hover,
  &:active,
  &:focus {
    background: alpha(mix(#fff, color, 75%), 0.8);
    
    @media (hover: none) {
      background: unset;
    }
  }
}
```

Desktop browsers and old mobile browsers use the first `background` property, new mobile browsers that support both `@media (hover)` and `unset` use the second property. `unset` [is supported in iOS 9.3+](http://caniuse.com/#feat=css-unset-value), so iOS versions 9.0–9.2 are still affected.

----

Now, as I don’t have an iOS device, I need help to test this solution. We should make sure that:

* The button doesn’t change the background when tapped.
* The button is activated from the first tap, not the second one. (The activation from the second tap means that iOS still tries to apply the unset hover styles on the first one. We should find another solution then.)

If you have an iOS 9.3+ device, I’d love if you could go to [the test page](http://iamakulov.com/demo/likely-no-hover/), make sure that both things and working properly and write back.

**Comment by iamakulov** [comment]
I’m removing the _Bug_ badge and adding the _Enhancement_ one because [people report](https://twitter.com/norweny/status/726811057570848768) that buttons work properly, and the only issue is the remaining `hover` color. The remaining color isn’t a bug.

**Comment by vitkarpov** [comment]
> Now, as I don’t have an iOS device, I need help to test this solution

Does the test page already have all the changes?

**Comment by iamakulov** [comment]
> Does the test page already have all the changes?

@vitkarpov, yes.

**Comment by iamakulov** [comment]
I’ve received a message on Twitter, and the current behavior is still buggy. This is how buttons looks after a tap (look at the top Twitter button):

![](https://cloud.githubusercontent.com/assets/2953267/15117595/f07f7048-1610-11e6-8fb2-c48b89f1f517.jpg)

Most likely, this is caused by `background: unset`, and we should explicitly specify the non-hover background instead.

**Comment by iamakulov** [comment]
Updated the test page: http://iamakulov.com/demo/likely-no-hover/.

**Comment by iamakulov** [comment]
People confirm it’s working.

#38
