### ISSUE TITLE
Declare the officially supported browsers

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#26]
Following #25.

At the moment, we don’t declare what browsers we support. This could be a turn-off point to potential Likely customers.

I’ve looked a bit into the code, and it seems Likely should properly work in all major browses including IE 10–11. However, a deeper check is required to find out the minimally supported IE version.

**Comment by iamakulov** [comment]
Checked the code with [jscc.info](http://jscc.info). Current code works in all major browsers including IE10+. IE9 and lower are not supported.

I believe we could declare the support for IE10+, Safari 9+ and latest versions of Chrome, Firefox and Edge.

@ilyabirman, is this OK?

**Comment by ilyabirman** [comment]
No problem

**Comment by iamakulov** [comment]
Done in #40.

**Comment by iamakulov** [comment]
Closed by an accident.
