### ISSUE TITLE
Get rid of config.protocol

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#27]
Now we explicitly use `config.protocol` constant to make right urls for apis. Seems the problem could be solved a little bit simpler: browsers can get the current protocol of the page if some url starts with `//`.

**Comment by vitkarpov** [comment]
@sapegin Hey! I noticed that you reacted agains the issue. Can you explain why this could be a bad decision?

**Comment by sapegin** [comment]
`//` do not allow you to easily test the script locally. You’ll need to run HTTP server to test relative protocols, or just use `protocol` variable.

**Comment by vitkarpov** [comment]
Do you mean to open `test.html` right from filesystem? Seems in this case `config.protocol` [equals](https://github.com/ilyabirman/Likely/blob/master/source/config.js#L5) `file:` and the case will be broken anyway.

**Comment by vitkarpov** [comment]
Oh, I get it now. `config.protocol` equals `http` in the case.

**Comment by sapegin** [comment]
Yep ;-)

**Comment by vitkarpov** [comment]
@iamakulov What do you think about it? Do we need likely to work locally?

**Comment by iamakulov** [comment]
@Sapegin, good point, thank you!

> Do we need likely to work locally?
@vitkarpov, yes. As we don’t use any automated testing, the only way to test the buttons is to open [`test.html`](https://github.com/ilyabirman/Likely/blob/master/test.html) locally and check the buttons there. Therefore the `protocol` is required.

**Comment by iamakulov** [comment]
I’m closing this issue at least until we introduce any automated testing. @vitkarpov, thank you for your interest :–)

**Comment by vitkarpov** [comment]
Absolutely! :)
