### ISSUE TITLE
Code style checker

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#28]
Seems it's time to add eslint to avoid comments about code style. Let's try to add some rules based on the current code.

**Comment by iamakulov** [comment]
Additionally, it’d be great to have an `.editorconfig` file to make IDEs follow our code style. Feel free to add it if you want and have time to do :-)

**Comment by vitkarpov** [comment]
Yep, you can set me as assignee.

**Comment by iamakulov** [comment]
Looks like I can assign only collaborators of the project, so no way :(

**Comment by vitkarpov** [comment]
Seems we're done here! (https://github.com/ilyabirman/Likely/pull/29)
