### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#30]
It would be convenient to check codestyle (and autotests in the future) on every pull in Travis, so we don't need to check out the branch and make sure that everything's okay every time.

**Comment by iamakulov** [comment]
Yup, great idea. Do you want to submit a PR?

**Comment by vitkarpov** [comment]
Yep :)

**Comment by iamakulov** [comment]
@ilyabirman, we’ll need your help here. You should register on [Travis CI](https://travis-ci.org/), import your GitHub repositories, enable Travis for this repository and enable the “Build only if .travis.yml is present” option in the repository settings. Could you do this please?

**Comment by iamakulov** [comment]
I’ve reached Ilya directly, he activated Travis: https://travis-ci.org/ilyabirman/Likely

**Comment by vitkarpov** [comment]
Great. Making a pr with travis config.

**Comment by iamakulov** [comment]
Done in #39
