### ISSUE TITLE
Update the project structure

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#32]
Following #31.
- [x] Move `test.html` to the `test` directory.
- [ ] Move the stylesheet into `sources`

**Comment by ilyabirman** [comment]
No way. All files should have extensions, no files should use caps lock. Sanity is above tradition.

**Comment by iamakulov** [comment]
Discussed this with @ilyabirman. The only change we’ll be doing is moving styles into `sources` directory. I’m dropping the following items from the list:

> - [ ] `readme.md` → `README.md`
> - [ ] `license.txt` → `LICENSE`
> - [ ] `sources` + `styles` → `src`
> - [ ] `release` → `dist`

and adding:

> - [ ] Move the stylesheet into `sources`
