### ISSUE TITLE
Reformat the project code according to the linting rules

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#34]
Following #29.

@vitkarpov, I’m going to do this on my own as I have some time. Are you OK with this?

**Comment by iamakulov** [comment]
Updated the code, will make the PR after merging #23.

**Comment by vitkarpov** [comment]
Absolutely. I woun't then.

**Comment by vitkarpov** [comment]
Make a pr :)

**Comment by iamakulov** [comment]
> Make a pr :)

@vitkarpov It’s too early yet because the code from #23 should also be processed in this PR.

**Comment by vitkarpov** [comment]
Do you mean that you make codestyle changes in #23 ?

**Comment by iamakulov** [comment]
Nope, I didn’t. I’m going to merge #23 before creating a PR for #34 (this issue) so that my PR for #34 can also reformat the code from #23. If I merge the PR for #34 now, I’ll have to re-run `npm run codestyle` and re-fix the issues again after merging #23.

On the other hand, I can open the PR for #34 now and then just update it when #23 is merged. I’ll do it this way.

**Comment by vitkarpov** [comment]
Okay :)

**Comment by iamakulov** [comment]
#35

**Comment by iamakulov** [comment]
Done.
