### ISSUE TITLE
Add link to demo

### ISSUE THREAD

**Issue by neonick** [ilyabirman/Likely#4]
http://ilyabirman.ru/projects/likely/

**Comment by volter9** [comment]
Thank you for pointing out!

**Comment by bolatovumar** [comment]
Может всё же на английскую версию поставим ссылочку?

http://ilyabirman.net/projects/likely/

**Comment by volter9** [comment]
Сначала нужно разобраться с основным языком репозитория :D

**Comment by bolatovumar** [comment]
@volter9  мне кажется, что нужно сделать всё с ориентацией на англоговорящую аудиторию. Русскоговорящие скорее всего уже знают про эти иконки от Бирмана. Было бы неплохо, если бы они набрали популярность и среди англосайтиков.

**Comment by volter9** [comment]
@bolatovumar I agree and Birman thinks that main language supposed to be English. I'll change link to English version. Thank you for pointing it out :)

**Comment by bolatovumar** [comment]
@volter9 sweet. Also, the tagline "The social sharing buttons that aren’t shabby" seems poorly worded (see the definition attached). Something like "Social media share buttons that don't suck" seems like a more suitable description.

![likely](https://cloud.githubusercontent.com/assets/1934678/10866633/81ac11a0-7ff5-11e5-9e47-cdf4e3d674a1.PNG)

**Comment by volter9** [comment]
@bolatovumar I'm not the one who made up this tagline :)
Although, I'll send him a message about the tagline.
