### ISSUE TITLE
Migrate to Webpack instead of Browserify

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#44]
Following #43.

There’s no real requirement for this yet, but this will make us more flexible in the future. PRs are welcome.

**Comment by andrew--r** [comment]
I'm ready to take this issue.

**Comment by iamakulov** [comment]
@andrew--r, great! Feel free to ping me if you need any help.

**Comment by mrnix** [comment]
See also http://rollupjs.org/
It might be more helpful to eliminate unused code.
Same feature also comes in Webpack 2

**Comment by iamakulov** [comment]
@andrew--r, if you feel you’re stuck or anything, please write back here so we can communicate and proceed further :-) Or if you want to drop this, it’s absolutely OK, just let us know so someone else could take this.

**Comment by mrnix** [comment]
I can also take it as a part of #48

**Comment by iamakulov** [comment]
Done in #58.
