### ISSUE TITLE
Add sharing text support to the Telegram button

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#46]
The Telegram button implemented in #23 can currently only share a specific URL. Telegram also allows to specify the message that will appear next to the URL, and @ilyabirman suggested that we implement it. Let’s do this.

I suggest to add the `data-text` attribute to the Telegram button which can be used to specify the message. The button code will look like following:

```html
<div class="telegram" data-text="Ilya Birman">Send</div>
```

The attribute should translate to the `text` parameter of the sharing URL. The URL will then look like following: [`https://telegram.me/share/url?url=http://ilyabirman.net&text=Ilya%20Birman`](https://telegram.me/share/url?url=http://ilyabirman.net&text=Ilya%20Birman). 

**PRs are welcome.** PR should also describe the sharing options [in the according section of Readme](https://github.com/ilyabirman/Likely#options).

**Comment by ilyabirman** [comment]
Share → Send

**Comment by iamakulov** [comment]
@ilyabirman, yep, you’re right, updated the issue.

BTW, I missed this in #40, made #47 to address this.
