### ISSUE TITLE
Migrate to ES6

### ISSUE THREAD

**Issue by mrnix** [ilyabirman/Likely#48]
The most obvious reason is that all _live_ projects written on it: working on a same syntax is much more easy than switching between different. With Babel, which can convert ES6/7 to ES5, no need to worry about compatibility with older browsers.

**Comment by iamakulov** [comment]
I _love_ this idea.

The infrastructure updates are currently blocked by #44, but we can migrate the code base and continue the work after it’s resolved.

If you want to submit a PR, feel free to :-)

**Comment by iamakulov** [comment]
Probably [Lebab](http://lebab.io/) could help with the code migration.

@mrnix, if you’ll be working on this, please write back here so nobody else takes this task. Anyway, I’m adding a `Help wanted` badge until anyone takes this.

**Comment by mrnix** [comment]
Yes, I'll take it

**Comment by iamakulov** [comment]
Cool!

**Comment by iamakulov** [comment]
@mrnix, #44 is now done. Feel free to start working on this. (Or please write back if you wouldn’t so someone else could take this.)

**Comment by iamakulov** [comment]
@mrnix, I’m adding the `Help wanted` badge back so someone else could take the issue. If you’re still working on this, just ping me :–)

**Comment by 7rulnik** [comment]
Will do it

**Comment by iamakulov** [comment]
@7rulnik, cool!

There’s one point though: we don’t want to do any major refactoring until we implement automatic tests (#73) because such changes can break something. If you submit your PR earlier than we merge #73, there’re chances that we’ll have to hold it for some time. Also, it’s possible that we do something in the `master` branch before we finish the tests, and you’ll need to update your PR.

Is this OK for you?

**Comment by 7rulnik** [comment]
@iamakulov yep

**Comment by 7rulnik** [comment]
What about webpack and gulp@4?
Do we need es6 there?

**Comment by iamakulov** [comment]
> @iamakulov yep

Cool then!

**Comment by iamakulov** [comment]
> What about webpack and gulp@4?
 Do we need es6 there?

Yes, but I think we don’t need to transpile them and can rely just on the Node 6 ES6 implementation.

**Comment by iamakulov** [comment]
Done in #79.
