### ISSUE TITLE
Likely as a React component

### ISSUE THREAD

**Issue by mrnix** [ilyabirman/Likely#49]
I think it could be good for sites with dynamic rendering

**Comment by vitkarpov** [comment]
Maybe different wrappers (react, polymer, angular component) should be in separate repos? Likely is an independent vanillajs library.

**Comment by iamakulov** [comment]
> Maybe different wrappers (react, polymer, angular component) should be in separate repos?
@vitkarpov, do you have ideas about how this could be implemented? Likely is tightly coupled with the real DOM, and I believe making it wrapper-agnostic is a complex task.

**Comment by iamakulov** [comment]
Generally, I like the idea, but I’m afraid it could be a bit complex to implement.

**Comment by vitkarpov** [comment]
> Likely is tightly coupled with the real DOM

if we speak about React I think it could be like this:

```js
const likely = require('ilyabirman-likely');

React.createClass('Likely', {
  componentDidMount() {
     this.update();
  },

  /**
   * Public method to update the component
   */
  update() {
    likely(this.node);
  },

  /**
   * Likely knows how to change itself,
   * React can't do anything useful
   */
  shouldComponentUpdate: () => false,

  render() {
    return <div ref={(node) => this.node = node;}>
        <div class="facebook">Share</div>
        <div class="twitter">Tweet</div>
        <div class="gplus">+1</div>
        <div class="vkontakte">Share</div>
        <div class="pinterest">Pin</div>
        <div class="odnoklassniki">Like</div>
        <div class="telegram">Send</div>
    </div>;
  }
})
```

But there's a problem: likely autoinitialize itseld on document loaded and with React it doesn't work as expected.

**Comment by vitkarpov** [comment]
Anyway I think in such case we need Likely organization with different repos:

- likely-core (Button constructor is here)
- likely-vanilla (autoinitialization on document load here)
- likely-react (React component here)
- ...

**Comment by ilyabirman** [comment]
(I’m frightened)

**Comment by iamakulov** [comment]
I’ll write about this a bit later. (I tend to close this currently.)

**Comment by vitkarpov** [comment]
> I tend to close this currently

+1 — seems very complicated right now.

**Comment by iamakulov** [comment]
> if we speak about React I think it could be like this:

Wow, an interesting approach. I’ve never worked on itegrating React with 3rd-party libraries before, and it seems this is a standard solution for integration. Both weird and beautiful at the same time.

**Comment by iamakulov** [comment]
> I tend to close this currently.

Well, this task is really complex and expensive. As there’re no more requests for this functionaly, I’m closing this now. I’d be glad to reopen this if we see more requests for React support though.
