### ISSUE TITLE
Likely doesn’t work with History API

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#51]
**Expected behavior:**
Likely buttons should catch the new URL when the page URL is changed with [`history.pushState()`](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method).

**Actual behavior:**
Buttons don’t update.

(Reported by @mrnix in an email.)

**Comment by iamakulov** [comment]
As a possible solution, we should listen for the `popstate` event and re-initialize the buttons on our own.

**Comment by vitkarpov** [comment]
Yep. Seems an appropriate solution.
