### ISSUE TITLE
Should we use only HTTPS for all services?

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#52]
We use the config protocol for urls in [some services](https://github.com/ilyabirman/Likely/blob/master/source/services/odnoklassniki.js#L12) and [the others are https only](https://github.com/ilyabirman/Likely/blob/master/source/services/facebook.js#L8).

Why we need `config.protocol` in such case? Maybe all services should be https only? Seems that all apis work on https and http-sites can request https without any penalty.

**Comment by vitkarpov** [comment]
@iamakulov What do you think?

**Comment by iamakulov** [comment]
> Maybe all services should be https only?

Yep, let’s switch to this.
