### ISSUE TITLE
Text isn't centered vertically in Firefox when “Minimum font size” is set

### ISSUE THREAD

**Issue by neongreen** [ilyabirman/Likely#57]
Firefox 45, Linux:

![screenshot from 2016-05-14 15-59-15](https://cloud.githubusercontent.com/assets/1523306/15268572/dc5b5db8-19ec-11e6-90e3-9e422d73c6f4.png)

It looks better if I remove the `.likely {font-size:0!important;}` rule:

![screenshot from 2016-05-14 16-01-30](https://cloud.githubusercontent.com/assets/1523306/15268584/25dd41cc-19ed-11e6-9111-bd2e21c38e00.png)

I wasn't able to replicate it on Firefox 45 on Windows, so say if there's anything I can do to help you debug it. Also, it looks the same when I run Firefox in safe mode (so I don't think it's caused by an extension).

Update: replicated on Windows as well.

**Comment by neongreen** [comment]
Turns out it only happens when the “Minimum font size” setting is set:

<img src="https://cloud.githubusercontent.com/assets/1523306/15269009/615e0aa8-19fa-11e6-8e08-f431dd61e3a6.png" width=50%>

**Comment by iamakulov** [comment]
Hi, thanks for the report!

I don’t know why the `font-size: 0` rule exists so I’ll try to test what changes without it in the next few days. If you want to submit a PR removing this rule, feel free to :-)

**Comment by neongreen** [comment]
It does change things a bit in Chrome. With the rule:

![screenshot from 2016-05-14 23-09-07](https://cloud.githubusercontent.com/assets/1523306/15270447/debd8932-1a28-11e6-8bc5-2e21cff8723b.png)

Without the rule:

![screenshot from 2016-05-14 23-09-58](https://cloud.githubusercontent.com/assets/1523306/15270453/fff383a4-1a28-11e6-970d-343c53ff248e.png)

(It's much easier to see things changing if you try disabling the rule with dev tools.)

I'll submit a PR just in case, but I wouldn't be surprised if it breaks something subtle.

**Comment by neongreen** [comment]
~~~
// Hide buttons until they are loaded
.likely {
  opacity: 0;
  font-size: 0 !important;
}

.likely_visible {
  opacity: 1;
  transition: opacity .1s ease-in;
}
~~~

If this rule is used to stop the buttons from taking space, we probably can't simply remove it.

**Comment by iamakulov** [comment]
> If this rule is used to stop the buttons from taking space, we probably can't simply remove it.

One option: we can unset the `font-size` rule when the buttons are made visible.

**Comment by iamakulov** [comment]
Most likely, there’re other ones.

**Comment by vitkarpov** [comment]
Maybe we should use `height` instead of `font-size` in this case?

```css
// Hide buttons until they are loaded
.likely {
  opacity: 0;
  height: 0;
}

.likely_visible {
  opacity: 1;
  height: auto;
}
```

**Comment by vitkarpov** [comment]
https://github.com/ilyabirman/Likely/pull/80

**Comment by vitkarpov** [comment]
@neongreen @iamakulov  Hey there! Seems the different way to hide buttons before they're loaded solves the problem. Check this out!
