### ISSUE TITLE
Как подгрузить свои иконки?

### ISSUE THREAD

**Issue by Novitsky** [ilyabirman/Likely#6]
Здравствуйте.
Как можно использовать иконочный шрифт вместо вшитых SVG?
Может ли мне кто-нибудь в этом помочь?

–––

Hello.
How can I use icon font instead of hardcoded SVG icons?
Could somebody help me with it?

**Comment by volter9** [comment]
Please, use the English language here. This repository isn't oriented only towards Russian-speaking developers :)

> Как можно использовать иконочный шрифт вместо вшитых SVG?

I think you'll have to hack the source, or replace those SVG icons with your  custom DOM nodes after onload with JS (keep in mind that Likely by default isn't visible until timeout or until all counters are loaded, you can use this time to override those icons). 

I can rearrange internals, so by default Likely is going to inject its own SVG icons, with ability to replace its icons with your own. What do you think?

**Comment by Novitsky** [comment]
Извините, но я не говорю по английски.
Я понимаю, что в этом проекте было принято решение ориентироваться на англоязычных пользователей. Может можно с вами, как-то по другому связаться?

**Comment by volter9** [comment]
volter925@gmail.com or volter_9 (skype)

**Comment by volter9** [comment]
For those who seeking the solution for this problem, there's a ~~solution~~ workaround:

If you would like to disable hardcoded SVG icons, you'll need to hack the code. All you need to do is to remove:
https://github.com/ilyabirman/Likely/blob/master/source/button.js#L122-L127

And replace it with:

```js
widget.innerHTML = button;
```

That's it. It'll disable the SVG icons from getting into `.likely__widget`, but SVG will remain in the source code. 

If you would like to remove it, you'll need to remove any lines mentioning `svg` variable in `source/services/index.js`. That's it. You might also want to remove `wrapSVG` function in `source/dom.js`.
