### ISSUE TITLE
Travis doesn’t catch some ESLint rules violation

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#61]
See https://github.com/ilyabirman/Likely/pull/59#discussion_r63289422 for example.

Most likely this is happening because `npm test` runs ESLint with `--fix` option, so ESLint fixes some rules locally on Travis and doesn’t generate any errors.

**Comment by vitkarpov** [comment]
According https://github.com/ilyabirman/Likely/pull/59#discussion_r63289529

I think we should remove `--fix` from package.json at all. It could be used externally:

```sh
$ npm run codestyle -- --fix
```

**Comment by vitkarpov** [comment]
So CI runs it without any arguments and developers do if it's needed.

**Comment by iamakulov** [comment]
> It could be used externally

This isn’t obvious. I, for example, have learned I could pass parameters this way only a couple of weeks ago. I’d better add the `check-codestyle` and `fix-codestyle` scripts (as we discussed in #59) just because it makes users’ life easier.

**Comment by vitkarpov** [comment]
> I could pass parameters this way only a couple of weeks ago

I did a minute ago :) But the idea that it's possible is obvious.

**Comment by vitkarpov** [comment]
I think make it more clear is a good idea anyway.
