### ISSUE TITLE
Google+ counters don’t work

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#66]
In February, a person reported that the Google+ counter doesn’t work, whereas [social-likes](https://github.com/sapegin/social-likes/) (the project Likely is built upon) fixed the counter [in 3.1.0](https://github.com/sapegin/social-likes/releases/tag/3.1.0). We need to:

* check that the bug is still actual,
* and find what changed and fix the problem on our side.

Original source from a letter:

> В Лайкли счетчик Гугл+ так и не заработал, хотя у Артема Сапегина в релизе от 10 января написано "Fix Google+ counter" https://github.com/sapegin/social-likes/releases И в Яндексе он тоже работает: https://tech.yandex.ru/share/

**Comment by vitkarpov** [comment]
@iamakulov works fine for me on a test page. At least we get a response from `share.yandex.net` and update the DOM with the given number.

What's the problem? The counter doesn't show up or it has a wrong value?

**Comment by iamakulov** [comment]
Compared the counter with the original Google+ share button, and our Google+ button works properly. Closing the issue as the bug seems not to be actual.

**Comment by vitkarpov** [comment]
I like such bugs :)

воскресенье, 3 июля 2016 г. пользователь Ivan Akulov написал:

> Compared the counter with the original Google+ share button, and our
> Google+ button works properly. Closing the issue as the bug seems not to be
> actual.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ilyabirman/Likely/issues/66#issuecomment-230151102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC3Nv5c9cp-mOIBehYuxzybfvR0xdr--ks5qR6t1gaJpZM4IpZ_w>
> .
>


-- 
Виктор.
