### ISSUE TITLE
Twitter and VK don’t receive the page title when Likely is placed before <title>

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#67]
The bug was reported in a letter in Jul 2015. The person says that when the Likely `<script>` tag is placed before `<title>`, Twitter and VK don’t receive the page title. We need to:

* check if this is still actual (most likely no because now Likely is initialized on a `load` event),
* and find the way to fix this is this is still actual.

Original source from the letter:

> Вчера, правда, обнаружил неприятность с которой пришлось долго разбираться. Если ссылки на подключаемые скрипты <script></script> идут раньше тега <title></title>, то в Твиттер и ВК не передаётся [в ссылке] заголовок страницы. Если ВК это не парит (можно заголовок совсем убрать из ссылки), то с Твиттером это проблема. Обнаружил долгим перебором всего, что может повлиять. Вот, смотришь на html-код — всё нормально, но не работает и всё тут. Возможно, этот можно как-то побороть в javascript’е, чтобы другие не мучались.

**Comment by vitkarpov** [comment]
@iamakulov Seems that we [compute `title` before DOM is fully loaded](https://github.com/ilyabirman/Likely/blob/aa600162c38d4625757ce2a6d71d20d50c2214bb/source/index.js#L50), so if the script is included before title is in the document, at this moment `document.title` is empty yet.

Maybe we should compute defaults settings within `likely. initiate` which executes on load event.

**Comment by vitkarpov** [comment]
https://github.com/ilyabirman/Likely/pull/70
