### ISSUE TITLE
Add an option to display zero in empty counters instead of nothing

### ISSUE THREAD

**Issue by andrew--r** [ilyabirman/Likely#68]
It would be great if we can specify some parameter like `data-count-empty="true"` on the `.likely` root.

This parameter should force likely to display `0` in counters if they're empty.

**Comment by andrew--r** [comment]
Of course, if social service doesn't support counters, it should display nothing (for example, telegram).

**Comment by iamakulov** [comment]
It’s a design decision. @ilyabirman, what do you think?

**Comment by iamakulov** [comment]
@andrew--r, why buttons without counters are inappropriate for you?

**Comment by andrew--r** [comment]
@iamakulov for example, I want to display a count of article shares on the main page of some blog. By default it looks a bit ugly (no fb shares):

![](https://habrastorage.org/files/670/5aa/0c7/6705aa0c7ac349e19238e6bbaa81c70d.png)

Rather than hide widgets with empty counters it would be better to display zero, I think:

![](https://habrastorage.org/files/7b8/33d/65a/7b833d65a2874522b6d76978d5046402.png)

**Comment by ilyabirman** [comment]
I don’t see how it makes the product better. I’d say don’t implement, at least until we see more requests for it. Looks like an unnecessary complication.

**Comment by iamakulov** [comment]
@andrew--r, as @ilyabirman suggested, I’m closing this and marking as `Won’t fix`. I’d be glad to reopen this though if there’s more interest.
