### ISSUE TITLE
Adds LinkedIn share button

### ISSUE THREAD

**Issue by nicolasbadia** [ilyabirman/Likely#69]
It would be nice to have a LinkedIn share button.

**Comment by vitkarpov** [comment]
@ilyabirman What do you think?

**Comment by iamakulov** [comment]
We’ve already discussed this in #16 and decided not it implement it yet. @nicolasbadia, I’m sorry, I’ll close this for now, but we can sure return to this if there is more interest.

**Comment by vitkarpov** [comment]
There're two requests already :)

**Comment by nicolasbadia** [comment]
Adding the button by manually integrating a PR is not really practical. Especially when using the library with bower.
If the size of the build (which btw will be only 0.70KB more) is an issue, maybe a solution would be to do several builds. One with just the main social networks, and another with all the social networks supported.
From my point of view, the argument that linkedin will be rarely use really depend of the targeted country. I personnaly had never heard of vkontakte and odnoklassniki until today...

**Comment by iamakulov** [comment]
Hm, we were originally targeting Russia and neighboring countries, where LinkedIn is rarely used. @nicolasbadia, how often do _you_ use LinkedIn (vs. Facebook or Twitter)? How common is it used in France or Europe in general?

**Comment by nicolasbadia** [comment]
LinkedIn is the first professional social network in France. I would say it is part of the 4 most used services here with FB, Twitter and G+.
