### ISSUE TITLE
rename initate to initiate

### ISSUE THREAD

**Issue by iamstarkov** [ilyabirman/Likely#7]
> \> initate
> \> Did you mean: initiate 
> — [Google](https://www.google.com/search?q=initate&ie=utf-8&oe=utf-8&gws_rd=cr&ei=cqpDVrPlJMSTsgHoi7mYAg)

**Comment by volter9** [comment]
Yeah, my bad. Could you propose the a PR? I'm kind of don't have access to the computer right now.
