### ISSUE TITLE
Clarify section about using API

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#82]
There's a section about using likely as a CommonJS-module, and there's just an example of using some method (`likely.initiate` in this case).

Apparently, it's not enough. Seems we need some API section. Now we have a couple of ways to interact with likely:

- `likely.initiate()`
- `likely(node)`

Each of this methods should be clarified.

**Comment by vitkarpov** [comment]
Relates to https://github.com/ilyabirman/Likely/issues/81#issuecomment-238529839

**Comment by iamakulov** [comment]
(Changing the labels: I tend to use `Enhancement` for the code improvements and `Docs` for the docs ones. When docs are changed, it’s (almost) always an enhancement, and code changes can also be new features or bug fixes.)

**Comment by vitkarpov** [comment]
Got it, thanks! :)

**Comment by iamakulov** [comment]
You know, I’d rather change the API, not the docs. Like, make `likely.initiate` also accept a node or an array of nodes. If a person uses Likely improperly, then it’s probably a fault of our API, not their.

**Comment by vitkarpov** [comment]
> Like, make likely.initiate also accept a node or an array of nodes.

Maybe, but it's breaking changes, so this could be done only in the next major version. For now, some docs could be useful (I guess, 2.0 is coming, but not so blazing fast as a regular pr)

**Comment by iamakulov** [comment]
We can change `initiate()` to have accept a node, a node and options, or options and deprecate `likely()`. This won’t be a breaking change and can be done earlier.

Note: we should add a deprecation warning when deprecating the method.

**Comment by vitkarpov** [comment]
Yep, seems it should work
