### ISSUE TITLE
Likely.initiate breaks counters of existing widgets

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#83]
**Steps to reproduce**

- load the test page
- perform likely.initiate() in console

**Actual**

Counters disappeared

**Expected**

Counters stay the same as after init

**Comment by iamakulov** [comment]
As mentioned in https://github.com/ilyabirman/Likely/issues/81#issuecomment-238573160, this is probably related to #75.

**Comment by vitkarpov** [comment]
Should check after merge, but as I get right the description of #75, it can't grasp how it could be connected for the first sight.

**Comment by iamakulov** [comment]
I didn’t write that, but the larger problem with #75 was that the counters got broken after calling `likely.initiate()`. The issue is about History API because it was reproduced with History first, and the History changes were handled by calling `likely.initiate()`.

**Comment by vitkarpov** [comment]
Ah, get it now. Will see anyway :)

**Comment by vitkarpov** [comment]
Done
