### ISSUE TITLE
Update Facebook API call

### ISSUE THREAD

**Issue by vitkarpov** [ilyabirman/Likely#86]
Now url

```
https://graph.facebook.com/fql?q=SELECT+total_count+FROM+link_stat+WHERE+url%3D%22http%3A%2F%2Filyabirman.ru%2Fprojects%2Flikely%2F%22&callback=random_fun_1
```

responses with a error

```
(#12) fql is deprecated for versions v2.1 and higher
```

Facebook counter doesn't work. We have to update API call.

**Comment by iamakulov** [comment]
According to @ilyabirman, we want to show the same number that the official “Like” button shows. Therefore, we can use this: http://stackoverflow.com/a/6821263/1192426.

This is a pretty critical stuff, BTW, 4 or 5 people have already reached me or @ilyabirman . It’s terrible we noticed this so late.

**Comment by iamakulov** [comment]
I’m releasing 2.1.3 once we finish this.
