### ISSUE TITLE
Fix bower.json main param: define release css and js location

### ISSUE THREAD

**Issue by vburlak** [ilyabirman/Likely#9]
When installing as a bower package, [wiredep](https://github.com/taptapship/wiredep) dependency manager automatically reads `bower.json`, then look into `main` param of installing package and include js and css in right places in parent projects.

But, when I've install likely via Bower, i've seen that lekely's main section looks like:
```json
"main": "source/index.js",
```
Currently in `main` param missed css file, and index.js file isn't work properly.
So, main param should looks like:
```json
"main": [
    "release/likely.css",
    "release/likely.js",
  ],
```
You can read more about `main` section in bower.json and how it should be defined [here](https://github.com/taptapship/wiredep#what-can-go-wrong)

Cheers!

**Comment by volter9** [comment]
Thanks for reporting the issue. I updated bower.json, I'll test it with wiredep and then close the issue in case of success.

**Comment by volter9** [comment]
It seems that everything works like a charm, Likely's main files are injected into HTML without any problems with wiredep.
