### ISSUE TITLE
Telegram button doesn’t let you choose the receiver on macOS

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#93]
> Likely 2.1.3, OS X 10.11.4, Telegram 2.23.50 official for macOS, кнопка при нажатии редиректит на страницу веб-интерфейса, а дальше просто открывает телеграм без возможности выбрать получателя сообщения.

Needs to be verified.

**Comment by vitkarpov** [comment]
That's what I found on the same system. There're several cases:

when Telegram app is running, you press the button and (maybe after confirmation that you want to open the app, I set it by default) you'll see:

![2016-09-26_19-55-30](https://cloud.githubusercontent.com/assets/3001791/18843867/767b211c-8423-11e6-9b86-d7082bbd67bb.png)

Seems everything okay, but if **the app was NOT running**, then you get the following under the same conditions:

![2016-09-26_19-56-27](https://cloud.githubusercontent.com/assets/3001791/18843918/b47ac6ca-8423-11e6-99ca-eaa7769abdb0.png)

The link has gone.

To make it work you have to manually press «share» on telegram share page:

![2016-09-26_19-56-53](https://cloud.githubusercontent.com/assets/3001791/18843944/d5d8dfd2-8423-11e6-83f4-ab723279ff80.png)

Then you'll see the first picture.

Do you get the same behaviour?

PS. I think the second case relates to some OS issues

**Comment by vitkarpov** [comment]
@iamakulov I think we should mention the origin's author

**Comment by vitkarpov** [comment]
I sent an email to author

**Comment by TrayHartred** [comment]
> The link has gone.

I have the same issue on the same system. Hope that the author will fix this bug.

**Comment by iamakulov** [comment]
Looks like a Telegram issue, not a Likely one.
