### ISSUE TITLE
Auto-enable the History API for npm package consumers

### ISSUE THREAD

**Issue by iamakulov** [ilyabirman/Likely#94]
Currently, Likely supports two different initialization scenarios. For users that just drop the Likely script into the page, we automatically initialize all the Likely buttons. For users that install Likely as a Node module and require it, we don’t do this as it’s rather harmful.

In #63, we decided to enable the History API support only for the just-drop-the-script users, but I think it’s rather bad. I think Node module consumers will also expect the API to just work, and I can’t come up with real examples of when “always enabled” can be harmful.

Let’s try to enable it by default for both scenarios without an option for disabling. I believe we can implement the disabling option if someone does experience real problems with it.

Cc @vitkarpov: interested if you have any thoughts about this.

**Comment by vitkarpov** [comment]
Yep, seems reasonable. I'm down with it, if you will.

**Comment by vitkarpov** [comment]
Is the current behaviour inconvenient? I mean, you have to enable it every time, right?

**Comment by iamakulov** [comment]
> Is the current behaviour inconvenient? I mean, you have to enable it every time, right?

Yeah. Currently, to enable the support, a user should require `history.js` and run `history.init()` manually.
