### ISSUE TITLE
Allow specifying image and description for the VK button

### ISSUE THREAD

**Issue by Banochkin** [ilyabirman/Likely#97]
Хочу предложить небольшую доработку кнопки для ВК. Сейчас при клике на кнопку идёт переход по ссылке vk.com/share.php?url={url}&title={title}. Но ВК поддерживает ещё передачу параметров description и image. Может их тоже можно добавить, по аналогии с Пинтерестом? Что-то вроде:

`<div class="vkontakte" data-media="картинка" data-desc="описание"></div>`

Проблема эта вскрылась после того, как заметил, что ВК на некоторых сайтах не позволяет выбрать картинку для ссылки при шеринге через vk.com/share.php. Если ему подсунуть картинку через vk.com/share.php?image={image} — всё ок, если не подсовывать ничего — в упор не видит картинки на странице.

**Comment by vitkarpov** [comment]
@iamakulov Sounds okay for me, what do you think?

**Comment by iamakulov** [comment]
@Banochkin Привет! Сорри за задержку.

Кнопка уже сейчас поддерживает эти атрибуты. `data-image="ссылка на изображение"` и `data-description="описание"` заработают так, как нужно. Мы задокументируем это, когда доберёмся.

**Comment by Banochkin** [comment]
@iamakulov спасибо! Работает)

**Comment by iamakulov** [comment]
Reopening until we add this to docs or anything.

**Comment by Banochkin** [comment]
Ok, sorry.
